### PR TITLE
Fixes to allow Intel 19.1.2 to use CICE

### PR DESCRIPTION
**Pull request by mathomp4**
For some reason, Intel really wasn't happy with opening a file everywhere.

### CODE REVIEW

**Comment by mathomp4** [comment]
I'll make this "ready for review", but I'll wait on some tests from @yvikhlya just to make sure fixing things for Intel 19.1.2 doesn't break things for Intel 18.0.5!

**Comment by mathomp4** [comment]
> Should it be tested with old compiler as well?

@zhaobin74 Yes. Probably a good idea. Main issue is that Intel 19.1 is non-zero-diff to Intel 18, so "works" is about all I can say for Intel 19. But if it's zero-diff with Intel 18, then at least we know this shouldn't be a cause of any change with Intel 19.

**Comment by zhaobin74** [comment]
@mathomp4, what I can do is to bring this change back to CVS version and do a zero-diff test with the old compiler (18.x). I expect to see zero-diff. If so, I'll approve. Will it be good enough?
> > Should it be tested with old compiler as well?
> 
> @zhaobin74 Yes. Probably a good idea. Main issue is that Intel 19.1 is non-zero-diff to Intel 18, so "works" is about all I can say for Intel 19. But if it's zero-diff with Intel 18, then at least we know this shouldn't be a cause of any change with Intel 19.

**Comment by mathomp4** [comment]
> @mathomp4, what I can do is to bring this change back to CVS version and do a zero-diff test with the old compiler (18.x). I expect to see zero-diff. If so, I'll approve. Will it be good enough?

Sounds good to me. I'm at the stage where I'm happy I can *run* MOM5/MOM6. I still rely on you all to make sure it's running correctly 😄

**Comment by zhaobin74** [comment]
@mathomp4, I am a bit confused about this fix. If you look at `ice_open` and `ice_open_nc` subroutine, there are already protections with `if (my_task == master_task)`  block. Why adding another layer solves problem?

**Comment by mathomp4** [comment]
> @mathomp4, I am a bit confused about this fix. If you look at `ice_open` and `ice_open_nc` subroutine, there are already protections with `if (my_task == master_task)` block. Why adding another layer solves problem?

@zhaobin74 I agree it is odd. My only thought is that some how calling a routine that does nothing on all processors but master causes...something? I was just trying everything I could to keep Intel 19.1.2 happy

**Comment by zhaobin74** [comment]
> > @mathomp4, I am a bit confused about this fix. If you look at `ice_open` and `ice_open_nc` subroutine, there are already protections with `if (my_task == master_task)` block. Why adding another layer solves problem?
> 
> @zhaobin74 I agree it is odd. My only thought is that some how calling a routine that does nothing on all processors but master causes...something? I was just trying everything I could to keep Intel 19.1.2 happy

Ok, I'll proceed with the zero-diff test. As long as Intel19 is happy, I am fine with that extra layer.

**Comment by yvikhlya** [comment]
> > > @mathomp4, I am a bit confused about this fix. If you look at `ice_open` and `ice_open_nc` subroutine, there are already protections with `if (my_task == master_task)` block. Why adding another layer solves problem?
> > 
> > 
> > @zhaobin74 I agree it is odd. My only thought is that some how calling a routine that does nothing on all processors but master causes...something? I was just trying everything I could to keep Intel 19.1.2 happy
> 
> Ok, I'll proceed with the zero-diff test. As long as Intel19 is happy, I am fine with that extra layer.

**Comment by mathomp4** [comment]
@yvikhlya Is there a reason you closed this?

**Comment by yvikhlya** [comment]
@mathomp4 Oh, I am sorry, I was writing a comment and pressed "close" by accident instead of "cancel". My fault.

**Comment by mathomp4** [comment]
> @mathomp4 Oh, I am sorry, I was writing a comment and pressed "close" by accident instead of "cancel". My fault.

No worries. I thought perhaps you found a better fix! 😄

**Comment by yvikhlya** [comment]
@mathomp4 This fix works with intel-18 and zero diff with 1.1.7.

**Comment by zhaobin74** [comment]
Zero-diff confirmed on CVS tag with Intel 18.

**Comment by mathomp4** [comment]
@zhaobin74 I think because I pushed something, your review was lost. Can you re-review this?

**Comment by zhaobin74** [comment]
@yvikhlya, can you push the cvs tag as well? My tag 'bzhao-s2s3-unstable' has it.

**Pull request merged**
