### PR TITLE
Add support for GEOS-IT in pyrob

### PR DESCRIPTION
**Pull request by mathomp4**
This PR adds support to `pyrob` to support the proposed/new GEOS-IT files.

### CODE REVIEW

**Review by rtodling — APPROVED** [review]
Seem good to me!

**Comment by mathomp4** [comment]
@rtodling Thanks. I'm waiting to hear back from Rob (not on GitHub as far as I can see 😄) as to what the higher ups want for the format. What is here works, but they might want different sorting? Not sure. I sent Rob two different GEOS-IT Word docs to evaluate. 

Though if there is a GMAO_Shared to be released soon, perhaps it's better to just get this in and then fix up sorting.

**Comment by rtodling** [comment]
Before we put out a final 5.29.3 tag (beyond the rt-... tag) we should work this in.

**Comment by mathomp4** [comment]
@rtodling Okay. I'll speak with @sdrabenh about getting it in. It can't exactly hurt anything!

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
