### PR TITLE
Proposed R21C changes 2024-01-29

### PR DESCRIPTION
**Pull request by sdrabenh**
Labeled as zero-diff from the GCM perspective. Updates originally from @elakkraoui

### CODE REVIEW

**Review by gmao-msienkie — APPROVED** [review]
The changes for GMAO_ods look good.
There is a separate pull request for the ODS changes which includes additional GPSRO types but those do not need to be in the R21C tag

**Review by mathomp4 — APPROVED** [review]

**Comment by mathomp4** [comment]
Interesting CI failure. I don't have time to investigate now, but since I approved, @sdrabenh can pull in if needed. I'll try and figure out how to fix up the R21C branch later

**Comment by sdrabenh** [comment]
@rtodling @elakkraoui these PR were initially marked as drafts for reviewing. Clicking the button "Ready for review" now so they are regular PRs. Please keep in mind CircleCI may fail for some of these PRs as we don't have an automated way to checkout latest within the R21C branches just yet.

**Comment by mathomp4** [comment]
> @rtodling @elakkraoui these PR were initially marked as drafts for reviewing. Clicking the button "Ready for review" now so they are regular PRs. Please keep in mind CircleCI may fail for some of these PRs as we don't have an automated way to checkout latest within the R21C branches just yet.

Indeed, I have a test to fix up the CI in #342 I'll monitor. If it works, we can merge it into this PR.

**Pull request merged**
