### PR TITLE
Support for ocean datasets using ExtData

### PR DESCRIPTION
**Pull request by sanAkel**
This PR adds capability to write out:
- netcdf kPAR (ocean color), sea surface temperature and sea ice concentration data files
- optionally also writes the above data in binary format

Documentation of the above code, example plotting scripts and notebooks to demo the datasets are also included.

**Note**: closes https://github.com/GEOS-ESM/GMAO_Shared/issues/243

**FYI** @lcandre2, @rcullath

### CODE REVIEW

**Review by tclune — DISMISSED** [review]
CMake changes ok.

**Review by sdrabenh — APPROVED** [review]

**Review by mathomp4 — APPROVED** [review]
Approve for CMake

**Comment by rcullath** [comment]
Thanks for letting me know.

~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~
Richard Cullather
ESSIC, University of Maryland at College Park
c/o NASA/GSFC Code 610.1 (Bldg. 33 / Rm. G114)      Tel: +1 301 614-5668
8800 Greenbelt Road                                 Fax: +1 301 614-6246
Greenbelt, MD 20771                   e-mail: ***@***.***

From: Matthew Thompson ***@***.***>
Sent: Thursday, March 17, 2022 3:26 PM
To: GEOS-ESM/GMAO_Shared ***@***.***>
Cc: Cullather, Richard I. (GSFC-610.1)[UNIVERSITY OF MARYLAND] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/GMAO_Shared] Support for ocean datasets using ExtData (PR #245)


@mathomp4 approved this pull request.

Approve for CMake

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGMAO_Shared%2Fpull%2F245%23pullrequestreview-913597737&data=04%7C01%7Crichard.cullather%40nasa.gov%7Ca3095ead77c64a01124c08da084bf7fe%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637831419622208650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MLbKqHCSLWL%2BCxDtk1k3Sk2aTM0FyHLXL9ytYzoRxvs%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPJB4W7A72JNTFYEIXYCPVDVAOBMLANCNFSM5OT3ZNOA&data=04%7C01%7Crichard.cullather%40nasa.gov%7Ca3095ead77c64a01124c08da084bf7fe%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637831419622208650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4dITx9Ul3TY5QdL8rhqdrHeiW4RpeOnrckPBaj%2BIHwU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crichard.cullather%40nasa.gov%7Ca3095ead77c64a01124c08da084bf7fe%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637831419622208650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=g0IHyKQJCzBoH17VvRnVS2cFo2dZppxcdhBWPS7YVO4%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crichard.cullather%40nasa.gov%7Ca3095ead77c64a01124c08da084bf7fe%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637831419622208650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Z2ibstNEJviQA58MMb2H6qk3bHoc3jGQxZjSPUI154E%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by rcullath** [comment]
Thanks for letting me know.

~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~
Richard Cullather
ESSIC, University of Maryland at College Park
c/o NASA/GSFC Code 610.1 (Bldg. 33 / Rm. G114)      Tel: +1 301 614-5668
8800 Greenbelt Road                                 Fax: +1 301 614-6246
Greenbelt, MD 20771                   e-mail: ***@***.***

From: Scott Rabenhorst ***@***.***>
Sent: Thursday, March 17, 2022 3:27 PM
To: GEOS-ESM/GMAO_Shared ***@***.***>
Cc: Cullather, Richard I. (GSFC-610.1)[UNIVERSITY OF MARYLAND] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/GMAO_Shared] Support for ocean datasets using ExtData (PR #245)


Merged #245<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGMAO_Shared%2Fpull%2F245&data=04%7C01%7Crichard.cullather%40nasa.gov%7C0d709365c0454cebc50d08da084c2b4c%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637831420475808581%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=x5vnGsRWxiTTIlGCH%2BfxqlQlyt9N481a%2FCA1I7SVTow%3D&reserved=0> into main.

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGMAO_Shared%2Fpull%2F245%23event-6261555731&data=04%7C01%7Crichard.cullather%40nasa.gov%7C0d709365c0454cebc50d08da084c2b4c%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637831420475818538%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bnol%2BVmKeZYAxnS84QWTZZviDcfZke2V%2Ftn7lm03i%2BI%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPJB4WYAUHGGIJMC3WQH7FTVAOBRVANCNFSM5OT3ZNOA&data=04%7C01%7Crichard.cullather%40nasa.gov%7C0d709365c0454cebc50d08da084c2b4c%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637831420475818538%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Sw%2BaFnpcwS4MmfxJL9FPkOhfE5%2FvE%2B3nUH3o2wCvQUw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crichard.cullather%40nasa.gov%7C0d709365c0454cebc50d08da084c2b4c%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637831420475828490%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JEXupfAPWNXEW2MS43RyMKgh5DQ6JFOjJDl9NvhlgbQ%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crichard.cullather%40nasa.gov%7C0d709365c0454cebc50d08da084c2b4c%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637831420475828490%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=njYGbgalINSgVSnNfQKDsm%2FrLy%2FRbiCu%2BYbq%2FADHX0k%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by rcullath** [comment]
Thanks for letting me know.

~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~~~~ ~~
Richard Cullather
ESSIC, University of Maryland at College Park
c/o NASA/GSFC Code 610.1 (Bldg. 33 / Rm. G114)      Tel: +1 301 614-5668
8800 Greenbelt Road                                 Fax: +1 301 614-6246
Greenbelt, MD 20771                   e-mail: ***@***.***

From: Scott Rabenhorst ***@***.***>
Sent: Thursday, March 17, 2022 3:22 PM
To: GEOS-ESM/GMAO_Shared ***@***.***>
Cc: Cullather, Richard I. (GSFC-610.1)[UNIVERSITY OF MARYLAND] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/GMAO_Shared] Support for ocean datasets using ExtData (PR #245)


@sdrabenh approved this pull request.

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGMAO_Shared%2Fpull%2F245%23pullrequestreview-913593323&data=04%7C01%7Crichard.cullather%40nasa.gov%7Ce24ba55ecb854eaa5d6b08da084b5c4b%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637831417009755591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2crpqsikACxvHJyczwVqSDq181flzGN9SGEPzHdvk0A%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPJB4W32RCVSW5HHS7EC7XTVAOA4BANCNFSM5OT3ZNOA&data=04%7C01%7Crichard.cullather%40nasa.gov%7Ce24ba55ecb854eaa5d6b08da084b5c4b%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637831417009755591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KPFZdsXz6%2FbqN%2FeB%2By8l5RYs6VYvkxbez5K%2FSs0QScM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crichard.cullather%40nasa.gov%7Ce24ba55ecb854eaa5d6b08da084b5c4b%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637831417009755591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CiBQFfQYYKqL5u99L5ZM5fPn%2FtcdcCNd8ZOa2rmzHck%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crichard.cullather%40nasa.gov%7Ce24ba55ecb854eaa5d6b08da084b5c4b%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637831417009755591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SUsbKRagvD%2B1T1XI34iO05GU%2BIF8J%2Bx7eq9BlioHLg8%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

**Pull request merged**
