### PR TITLE
New definition for KX=255 SSEC/WISC LEO-GEO winds

### PR DESCRIPTION
**Pull request by gmao-msienkie**
KX=255 had previously been assigned to NESDIS picture triplet winds, a historic data type not seen for many years.  Recently the GSI was modified to assign KX=255 to the LEO-GEO winds from Wisconsin SSEC.  This pull request adds information about the LEO-GEO winds to two files with kx table information.  It also modifies the metadata written to ODS files to include information about LEO-GEO winds.  
While this data is not currently assimilated in the GEOS DAS, it does show up in the recent x0048 test.  Adding this information will avoid confusion related to the new data.  "What!  KX 255?  We haven't had picture triplet data in years!"

### CODE REVIEW

**Comment by mathomp4** [comment]
Note to @gmao-msienkie, I think the CI failure was due to being out of date with `main`. I pressed the button. If you have any further changes to make, make sure you do a `git pull` before pushing anything.

**Review by rtodling — DISMISSED** [review]
I don't have a problem w/ this going in.

**Comment by rtodling** [comment]
I just updated the changelog w/ info on this change.

**Review by gmao-msienkie — COMMENTED** [review]
Looks fine to me.  Thanks, Ricardo.

**Review by mathomp4 — APPROVED** [review]
Adding a review for @GEOS-ESM/gcm-gatekeepers . Both @sdrabenh and myself know this code doesn't affect the GCM, so it's trivially zero-diff for us.

**Pull request merged**
