### PR TITLE
Feature/jstassi/#278 gmao etc

### PR DESCRIPTION
**Pull request by gmao-jstassi**
Updated obsys_rc.py, check_obsysrc.py, and associated unittests to Python 3.
Features added to cmpdir.pl script.

### CODE REVIEW

**Comment by gmao-jstassi** [comment]
Ricardo, these updates are utility programs that do not have any impact on DAS processing.

**Review by rtodling — CHANGES_REQUESTED** [review]
What are the files obsys-testX.rc.err ?? They seem to be personalized! Why?

Please rename the script test.csh to a more specific name.

**Comment by gmao-jstassi** [comment]
Ricardo, I do not see a file named obsys-testX.rc.err. I am not good with git, so maybe I messed up something, but could you point me to where that file is? Thanks.

The test.csh file is a wrapper script for all the Python test scripts under the unittests directory, which in this case is just one, but that is why it has a generalized name. Nothing in the unittests directory gets put into the build. The only purpose for these files is to test the Python scripts in the GMAO_etc directory, to verify that they still give expected results after being modified.

**Comment by rtodling** [comment]
Joe, just click on the tab for Files Changed near the top of the PR along the same line as Conversation Commits .. etc you will see the files I am talking about. Maybe they got in by mistake.

**Comment by sdrabenh** [comment]
@gmao-jstassi and @rtodling, please let me know the status of this PR. Does more work need to be done here, or should this PR be closed? Obviously, this doesn't affect the GCM, so I'm happy to take it or leave it. However, I don't won't to approve and merge this unless @rtodling is satisfied with these changes.

**Review by sdrabenh — APPROVED** [review]

**Review by mathomp4 — APPROVED** [review]

**Pull request merged**
