### PR TITLE
Sync latest das branch feature/rtodling/g530 into main

### PR DESCRIPTION
**Pull request by sdrabenh**

### CODE REVIEW

**Review by tclune — APPROVED** [review]
CMake changes ok.

**Review by rtodling — APPROVED** [review]
This looks good to me. It is zero diff to FP-like settings.

**Comment by rtodling** [comment]
Thanks Scott

**Review by mathomp4 — APPROVED** [review]
I'll approve just to make it a clean sweep. 😄

**Comment by rtodling** [comment]
If someone can put a version number on this I can update the DAS components accordingly. Thanks.

**Comment by sdrabenh** [comment]
> If someone can put a version number on this I can update the DAS components accordingly. Thanks.

Will do. Thanks for approval @rtodling

**Pull request merged**
