### PR TITLE
Feature/bweir/#305 codas

### PR DESCRIPTION
**Pull request by briardew**
My additions to GMAO_ods to include trace gas support for CoDAS. Also includes more OMPS and AMSR support from Ricardo's rt_g530_1.6.0_merge tag.

### CODE REVIEW

**Comment by mathomp4** [comment]
@briardew When you have a chance, can you resolve the conflicts here?

**Comment by mathomp4** [comment]
As this is more in @rtodling's realm, once he approves, I'll approve for GCM Gatekeepers.

**Comment by rtodling** [comment]
Brad, I will pull this and test on my end - to corroborate (or not) the zero-diff label.

**Review by rtodling — APPROVED** [review]
Looks good to me - passes zero-diff test for ADAS

**Review by mathomp4 — APPROVED** [review]

**Pull request merged**
