### PR TITLE
Bug fix for issue #99: Edge level arrays out-of-bounds in Lighting_mod

### PR DESCRIPTION
**Pull request by christophkeller**
This is a bug fix for the following issue: https://github.com/GEOS-ESM/GMAO_Shared/issues/99

Arrays ple and cnvMfc are now referenced using the indices LM:0 (instead of LM+1:1):

```
      pleHemco(:,:,1:KM) = ple(:,:,LM:0:-1)
      cnvMfcHemco(:,:,1:KM) = cnvMfc(:,:,LM:0:-1)
```

Similarly, the index was shifted by -1 for array geoPotHeight so that it now spans the valid range:

```
      do levCount=1,LM
         gridBoxHeightHemco(:,:,levCount) = geoPotHeight(:,:,levCount-1) - geoPotHeight(:,:,levCount)
      enddo
```

### CODE REVIEW

**Comment by atrayano** [comment]
This fix is OK, I was thinking we can be more general, and use LBOUND/UBOUND to be absolutely sure. But for GEOS, this fix is totally fine. Thanks!

**Comment by mathomp4** [comment]
@christophkeller Is this zero-diff or non-zero-diff?

**Comment by atrayano** [comment]
@mathomp4 This is bugfix - if the lightning code was exercised, if would have crashed, while new PR fixes it. If it is not exercised, then of course it should be a zero-diff

**Comment by mathomp4** [comment]
Okay. Just wondering how to label it. And I suppose I can figure out a Changelog message for this ("make code work").

**Comment by christophkeller** [comment]
The bug fix prevents an out-of-bounds error, so maybe this could be the Changelog message ("prevent out-of-bounds error")

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
