### PR TITLE
Changes needed to allow use of aggressive flags with GEOS

### PR DESCRIPTION
**Pull request by mathomp4**
Activate by using `-DCMAKE_BUILD_TYPE=Aggressive`

### CODE REVIEW

**Comment by mathomp4** [comment]
I tried this without the changes to ESMA_cmake and ecbuild and it was happy.

**Review by tclune — DISMISSED** [review]
I think a character is required in column 6

**Comment by mathomp4** [comment]
> I think a character is required in column 6

I think in [fixed-form](https://www.openmp.org/spec-html/5.1/openmpsu17.html#x32-310002.1.1) it is, but `mod_four.F90` is hopefully free-form, and so [the standard doesn't seem to require that](https://www.openmp.org/spec-html/5.1/openmpsu17.html#x32-310002.1.1).

**Comment by tclune** [comment]
Oops.   I actually checked before I hit return.  Thought I had deleted the comment, but apparently not.  Sorry.

**Review by sdrabenh — APPROVED** [review]

**Review by bena-nasa — APPROVED** [review]

**Pull request merged**
