### PR TITLE
Bugfix/jstassi/#364 g5 modules perl wrapper

### PR DESCRIPTION
**Pull request by gmao-jstassi**
Updated g5_modules_perl_wrapper to remove loadmodules option when calling g5_modules, since the option is no longer valid after an update to g5_modules.

### CODE REVIEW

**Comment by mathomp4** [comment]
@gmao-jstassi a few things. 

First, there is a conflict here. I think I can fix it on the CLI if you are fine with that.

Second, this repo requires Changelog entries on non-trivial PRs. Can you add one that encompasses all that is happening here (which seems a lot).

Third, please add a `0 diff` or  `non 0-diff` label so we know what to expect when testing.

**Comment by gmao-jstassi** [comment]
Matt,

Let me withdraw my pull request. I only made a few minor changes to one file, but I branched off from whatever I got when I grabbed Ricardo’s tag. Probably my changes should go back to Ricardo rather than to main. Can I send him a pull request, or does he have to handle it manually?

Sorry, I am still trying to figure out the complexities of git.

Thanks.
Joe

From: Matt Thompson ***@***.***>
Reply-To: GEOS-ESM/GMAO_Shared ***@***.***>
Date: Tuesday, December 24, 2024 at 8:30 AM
To: GEOS-ESM/GMAO_Shared ***@***.***>
Cc: Joe Stassi ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [GEOS-ESM/GMAO_Shared] Bugfix/jstassi/#364 g5 modules perl wrapper (PR #365)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



@gmao-jstassi<https://github.com/gmao-jstassi> a few things.

First, there is a conflict here. I think I can fix it on the CLI if you are fine with that.

Second, this repo requires Changelog entries on non-trivial PRs. Can you add one that encompasses all that is happening here (which seems a lot).

Third, please add a 0 diff or non 0-diff label so we know what to expect when testing.

**Comment by mathomp4** [comment]
We looked and it looks like `feature/rtodling/milan` was the parent branch of this branch. It does seem like the tag `g5.41.3` was based on this branch too:
```
2024-12-23 18:13 -0500 Joe Stassi        o [bugfix/jstassi/#364-g5_modules_perl_wrapper] {origin/bugfix/jstassi/#364-g5_modules_perl_wrapper} update g5_mod
2024-10-29 12:49 -0400 Ricardo Todling   o <g5.41.3> these started giving trouble after a number of cycles - something is going on that I do not fully unde
2024-10-14 10:35 -0400 Ricardo Todling   o [feature/rtodling/milan] {origin/feature/rtodling/milan} <g5.41.2> now live in GMAO_mksi
...
```

**Review by rtodling — COMMENTED** [review]
Thanks for working on this. This is all good except that it cannot be aimed at the branch you point it to: feature/rtodling/milan ... this is a little complicated w/ how gmao-shared is behind in some respects and ahead in others ... let's aim at develop; and I will merge this into some other branch that becomes part of the 5.41 series.

**Pull request merged**
