### PR TITLE
Updated remapping consistent with FV3

### PR DESCRIPTION
**Pull request by mathomp4**
Based off of feature/wmputman/nh_gfdlmp_updates

### CODE REVIEW

**Review by bena-nasa — APPROVED** [review]

**Comment by tclune** [comment]
Matt - who is the "Lead" for the "Needs Lead Approval"?

**Comment by mathomp4** [comment]
> Matt - who is the "Lead" for the "Needs Lead Approval"?

This would be @wmputman I think. My guess is this is part of the next non-zero-diff release from @sdrabenh ?

**Comment by sdrabenh** [comment]
> > Matt - who is the "Lead" for the "Needs Lead Approval"?
> 
> This would be @wmputman I think. My guess is this is part of the next non-zero-diff release from @sdrabenh ?

I'm not sure where this PRs stands at this point. I will defer to @wmputman as these are his changes.

**Comment by wmputman** [comment]
I was just trying to understand why this wasn't already in develop.  We tested this a long while ago

**Comment by wmputman** [comment]
Can someone comment on why we have Gmap and Remap?  GEOS_GmapMod.F90 and GEOS_RemapMod.F90

**Comment by sdrabenh** [comment]
@wputman I could be wrong, but I don't think this replay ran using this remapping. Do you recall if the tests were correct?

**Comment by wmputman** [comment]
OK, coming back to me.. this pull request looks kind of incomplete.  Should resemble this code:

[https://github.com/GEOS-ESM/GMAO_Shared/commit/eb2728178b38e50afe11eb0d55983512071765ca#diff-e00eef331bf15bbd93de7a719b4e5a74e90f7aae913787c76b32e63625980c5f](url)

**Comment by wmputman** [comment]
https://github.com/GEOS-ESM/GMAO_Shared/commit/eb2728178b38e50afe11eb0d55983512071765ca#diff-e00eef331bf15bbd93de7a719b4e5a74e90f7aae913787c76b32e63625980c5f

**Comment by sdrabenh** [comment]
@wmputman the experiment for this PR and [#371](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/371) at:
/discover/nobackup/projects/gmao/g6dev/sdrabenh/Replay_Experiments/JD-20201029_GC371-SH135_C360_RPLY_E5
and posted at:
https://gmao.gsfc.nasa.gov/intranet/research/modeling/agcm/geos5/JD-20201029_GC371-SH135_C360_RPLY_E5/

If everything looks good we can merge, or I can re-run if we need to activate differently

**Comment by wmputman** [comment]
I will incorporate this change in my updates sequence

**Comment by mathomp4** [comment]
> [eb27281#diff-e00eef331bf15bbd93de7a719b4e5a74e90f7aae913787c76b32e63625980c5f](https://github.com/GEOS-ESM/GMAO_Shared/commit/eb2728178b38e50afe11eb0d55983512071765ca#diff-e00eef331bf15bbd93de7a719b4e5a74e90f7aae913787c76b32e63625980c5f)

Bill,

Would you like me to pull these extra changes into this branch/PR?

**Comment by mathomp4** [comment]
@wmputman Do you have these edits in your own L91 branch? If so, I might as well close this and delete my branch.

**Pull request closed without merging**
